version: '3.7'

services:
  currency-exchange:
    image: mailsonymathew/mmv2-currency-exchange-service-v2:0.0.1-SNAPSHOT
# The memory set aside for the microservice    
    mem_limit: 700m
# The port on which the microservice is exposed     
    ports:
      - "8000:8000"
# The network being used commonly by all microservices. This NW is defined towards the end.       
    networks:
      - currency-network
# The dependency of the microservice on any other       
    depends_on:
      - naming-server
# The environment configuration. Here we are specifying the eureka naming server url by replacing local host with 'naming-server' as specified below. Also the env name must be in camel case without underscores!!!      
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka

      
  naming-server:
    image: mailsonymathew/mmv2-netflix-eureka-naming-server-v2:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network      

# Networks to be created to facilitate communication between containers
networks:
  currency-network:  